// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6_9GdgAEKFRPlR-KUSQCAtDwfQzZyL4I',
    appId: '1:847669236909:web:f82bbc7eedd2a6ecf06224',
    messagingSenderId: '847669236909',
    projectId: 'loginact5',
    authDomain: 'loginact5.firebaseapp.com',
    storageBucket: 'loginact5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjsjdncteWmMSg4BxuV2UNAmhkgLDgdF8',
    appId: '1:847669236909:android:32421d2c6536681cf06224',
    messagingSenderId: '847669236909',
    projectId: 'loginact5',
    storageBucket: 'loginact5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGVo5HJziKdNA2cw--pTxiYj2ErrFZWc',
    appId: '1:847669236909:ios:54b0fc208cfc6a4cf06224',
    messagingSenderId: '847669236909',
    projectId: 'loginact5',
    storageBucket: 'loginact5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGVo5HJziKdNA2cw--pTxiYj2ErrFZWc',
    appId: '1:847669236909:ios:3a4cb61cb352f66cf06224',
    messagingSenderId: '847669236909',
    projectId: 'loginact5',
    storageBucket: 'loginact5.firebasestorage.app',
    iosBundleId: 'com.justhin.app',
  );

}